### ISSUE TITLE
Error during whitebox.Runner()

### ISSUE THREAD

**Issue by bond9779** [giswqs/whitebox-python#16]
* whitebox version:  1.2.0
* Python version: 3.5
* Operating System: ubuntu 16.04

### Description

Describe what you were trying to get done.
.Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Documents/venvs/base_all/lib/python3.5/site-packages/whitebox/wb_runner.py", line 1316, in Runner
    wbr = WbRunner(tool_name)
  File "/home/Documents/venvs/base_all/lib/python3.5/site-packages/whitebox/wb_runner.py", line 767, in __init__
    self.create_widgets()
  File "/home/Documents/venvs/base_all/lib/python3.5/site-packages/whitebox/wb_runner.py", line 789, in create_widgets
    self.get_tools_list()  
  File "/home/Documents/venvs/base_all/lib/python3.5/site-packages/whitebox/wb_runner.py", line 1022, in get_tools_list
    self.tool_name = self.tools_list[0]
IndexError: list index out of range

### What I Did
whitebox.Runner()
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
I just tested it on two of my Manjaro Linux computers, and it works fine. 

Could you try [conda](https://docs.conda.io/en/latest/miniconda.html) to install the whitebox package? 

```
conda create -n py37 python
conda activate py37
pip install whitebox
python
import whitebox
whitebox.Runner()
```
